
set nocompatible

" Kid Tested.  Python approved.
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4

set autoindent
set ignorecase
set smartcase

set scrolloff=3

set visualbell
set noerrorbells

set hidden
set ruler
set title
set showcmd

set showmatch
set hlsearch
set incsearch

set history=1000
set undolevels=1000
set wildignore=*.swp,*.bak,*.pyc

" Enable Pathogen
call pathogen#infect()

syntax on

" Autocomplete fun
filetype on
filetype plugin indent on
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#Complete

" Change autocomplete to Control-Space
inoremap <Nul> <C-x><C-o>

" Automatically close the preview buffer generated by Autocomplete
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif 
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" Woo colors...
if &term =~ "xterm"
  "256 color --
  let &t_Co=256
endif

if &term =~ "screen"
  "256 color --
  let &t_Co=256
endif

colorscheme darkburn


