---

# Host dependencies that require root to install
- hosts: localhost
  connection: local
  user: root
  sudo: True

  tasks:

    - name: ubuntu - apt packages
      apt: name={{ item }} state=installed
      when: ansible_distribution == "Ubuntu"
      with_items:
        - exuberant-ctags
        - git
        - python-virtualenv
        - python-dev
        - python-pkg-resources
        - python-setuptools

    - name: global python packages for vim modules
      pip: name={{ item }} state=present
      with_items:
        # Ubuntu 12.04 LTS needs pip installed distribute
        - distribute
        - flake8

  
